version: '3.8'
services:
  # MySQL 8.0 service
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      # 设置root用户的密码
      - MYSQL_ROOT_PASSWORD=123456
      # 设置时区
      - TZ=Asia/Shanghai
    networks:
      - ell
    volumes:
      - mysql-storage:/var/lib/mysql
      # 初始化数据库的脚本
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  
  # Redis 5.0 service
  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ell
    command: redis-server --requirepass 123456

networks:
  ell:
    driver: bridge

volumes:
  mysql-storage: