version: '3.8'
services:
  # MySQL 8.0 service
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      # 设置root用户的密码
      - MYSQL_ROOT_PASSWORD=123456
      # 设置时区
      - TZ=Asia/Shanghai
    networks:
      - ell
    volumes:
      - mysql-storage:/var/lib/mysql
      # 初始化数据库的脚本
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      # 初始化Quartz数据库的脚本
      - ./init-quartz.sql:/docker-entrypoint-initdb.d/init-quartz.sql
  
  # Redis 5.0 service
  redis:
    image: redis:5.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ell
    command: redis-server --requirepass 123456
  
  # RecketMQ 5.0 service
  namesrv:
    image: apache/rocketmq:5.3.1
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      - ell
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.3.1
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - namesrv
    networks:
      - ell
    command: sh mqbroker
  proxy:
    image: apache/rocketmq:5.3.1
    container_name: rmqproxy
    networks:
      - ell
    depends_on:
      - broker
      - namesrv
    ports:
      - 8080:8080
      - 8081:8081
    restart: on-failure
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    command: sh mqproxy

networks:
  ell:
    driver: bridge

volumes:
  mysql-storage: